[package]
name = "atuin-desktop-templates"
workspace = "../.."
version.workspace = true
edition.workspace = true

[dependencies]
minijinja = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
